apiVersion: v1

kind: Secret
metadata:
  annotations:
    "jenkins.io/credentials-description" : "API TOKEN FOR GITLAB"

  labels:
    "jenkins.io/credentials-type": "secretText"
  name: secret-name1

type: Opaque
stringData:
  text: c-6vQMnRBqtrDOQmvnf-kjtHXpZs0jhdEWM
